# -*- coding: utf-8 -*-
"""breast cancer detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajqlWusbUcSo2Kr41mXE4KFCUuQvMaa8
"""

import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df=pd.read_csv("wdbc.data", header=None)

X = df.iloc[:, 2:]
y = df.iloc[:, 1]

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

model = SVC(max_iter=40)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

'''
import matplotlib.pyplot as plt

data = pd.read_csv("wdbc.data", header=None)

# Assign standard Breast Cancer Wisconsin column names
columns = [
    "id", "diagnosis",
    "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean",
    "compactness_mean", "concavity_mean", "concave_points_mean", "symmetry_mean",
    "fractal_dimension_mean",

    "radius_se", "texture_se", "perimeter_se", "area_se", "smoothness_se",
    "compactness_se", "concavity_se", "concave_points_se", "symmetry_se",
    "fractal_dimension_se",

    "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst",
    "compactness_worst", "concavity_worst", "concave_points_worst", "symmetry_worst",
    "fractal_dimension_worst"
]
data.columns = columns

data["diagnosis"] = data["diagnosis"].map({"M": 1, "B": 0})

data = data.drop("id", axis=1)

correlations = data.corr()["diagnosis"].drop("diagnosis").sort_values(ascending=False)

plt.figure(figsize=(12, 6))
correlations.plot(kind="bar")
plt.title("Correlation of Features with Diagnosis (Malignant=1, Benign=0)")
plt.xlabel("Features")
plt.ylabel("Correlation Coefficient")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()
'''
'''
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = pd.read_csv("wdbc.data", header=None)

columns = [
    "id", "diagnosis",
    "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean",
    "compactness_mean", "concavity_mean", "concave_points_mean", "symmetry_mean",
    "fractal_dimension_mean",
    "radius_se", "texture_se", "perimeter_se", "area_se", "smoothness_se",
    "compactness_se", "concavity_se", "concave_points_se", "symmetry_se",
    "fractal_dimension_se",
    "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst",
    "compactness_worst", "concavity_worst", "concave_points_worst", "symmetry_worst",
    "fractal_dimension_worst"
]
data.columns = columns

data["diagnosis"] = data["diagnosis"].map({"M": 1, "B": 0})
data = data.drop("id", axis=1)

correlations = data.corr()["diagnosis"].drop("diagnosis").sort_values(ascending=False)
sorted_features = list(correlations.index)

models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "SVM (rbf)": SVC(kernel="rbf", gamma="scale"),
    "Random Forest": RandomForestClassifier(n_estimators=150, random_state=42)
}

results = {name: [] for name in models.keys()}
num_features_list = []

for k in range(2, len(sorted_features) + 1):
    selected = sorted_features[:k]
    X = data[selected]
    y = data["diagnosis"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)
    num_features_list.append(k)
    for name, model in models.items():
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds)
        results[name].append(acc)

plt.figure(figsize=(10, 6))
for name, acc_list in results.items():
    plt.plot(num_features_list, acc_list, marker='o', label=name)
plt.title("Accuracy vs Number of Top Correlated Features")
plt.xlabel("Number of Features")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

for name, acc_list in results.items():
    best_k = num_features_list[acc_list.index(max(acc_list))]
    print(f"{name}: Best accuracy = {max(acc_list):.4f} using {best_k} features")
'''