# -*- coding: utf-8 -*-
"""heartdiseaseprediction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_X3V2pPeiYG-xNcJImY08fcp-dbE6B7V
"""

import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("heart.csv")

y = df["target"]
X = df.drop("target", axis=1)

# 1. Split first
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# 2. Scale second
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train) # Learn and transform training data
X_test = scaler.transform(X_test)       # Use training parameters to transform test data

# 3. Model
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# 4. Evaluate
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")