# -*- coding: utf-8 -*-
"""loanapproval

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNPqdk_DbqD4vsThPLym4QYFX59Nz9kF
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import plot_tree # Visualize tree
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df= pd.read_csv("loan_approval.csv")
df.columns = df.columns.str.strip() # Clean column names

y= df["loan_status"]
X= df.drop(['loan_id', 'loan_status'], axis=1)

x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=10)

model= DecisionTreeClassifier(criterion='entropy', max_depth=12, class_weight={0:2, 1:1})
model.fit(x_train,y_train)

y_pred= model.predict(x_test)
'''
plt.figure(figsize=(20,10))  # optional: adjust size
plot_tree(model,
          feature_names=X.columns,  # column names
          class_names=['Rejected', 'Approved'],  # target classes
          filled=True,              # color nodes by class
          rounded=True,             # rounded boxes
          fontsize=12)
plt.show()
'''

print(f"Accuracy: {accuracy_score(y_test,y_pred)}")
print(f"Confusion Matrix:\n {confusion_matrix(y_test,y_pred)}")
print(f"Classification Report:\n {classification_report(y_test,y_pred)}")

'''
depth= range(1,100)
accuracies=[]
for d in depth:
    model = DecisionTreeClassifier(max_depth=d, random_state=10)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

# Plot
plt.figure(figsize=(25,9))
plt.plot(depth, accuracies, marker='o', linestyle='-', color='blue')
plt.title('Decision Tree Accuracy vs Max Depth')
plt.xlabel('Max Depth')
plt.ylabel('Accuracy')
plt.xticks(depths)
plt.grid(True)
plt.show()
'''