# -*- coding: utf-8 -*-
"""mall customers(kmeans)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMkvJ3cx084rktxCFWX4iwa2ARnRkfUq
"""

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score

df= pd.read_csv("Mall_Customers.csv")

X = df[['Age', 'Annual Income (k$)', 'S_score']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


silhouette_scores = []

# Try k from 2 to 10 (you can adjust the range)
for k in range(2, 30):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    silhouette_scores.append(score)

# Print scores
for i, score in enumerate(silhouette_scores, start=2):
    print(f'k={i}, Silhouette Score={score:.3f}')

plt.plot(range(2, 30), silhouette_scores, marker='o')
plt.xlabel('Number of clusters (k)')
plt.ylabel('Silhouette Score')
plt.title('Finding Optimal k using Silhouette Score')
plt.show()

kmeans = KMeans(n_clusters= 6, random_state=42)
labels = kmeans.fit_predict(X_scaled)

df['Cluster'] = labels

plt.figure(figsize=(8,6))

# Sort cluster labels
for cluster in sorted(df['Cluster'].unique()):
    clustered_data = df[df['Cluster'] == cluster]
    plt.scatter(clustered_data['Annual Income (k$)'],
                clustered_data['S_score'],
                label=f'Cluster {cluster}',
                s=50)

plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score')
plt.title('Customer Segments (K-Means Clustering)')
plt.legend()
plt.show()

'''
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Load dataset
df = pd.read_csv("Mall_Customers.csv")

# Features for clustering
X = df[['Age', 'Annual Income (k$)', 'S_score']]

# Normalize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Fit K-Means
kmeans = KMeans(n_clusters=18, random_state=42)  # you can change k
labels = kmeans.fit_predict(X_scaled)

df['Cluster'] = labels

# Apply PCA to reduce 4D to 2D for plotting
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Plot clusters in 2D
plt.figure(figsize=(8,6))
for cluster in sorted(df['Cluster'].unique()):
    plt.scatter(X_pca[df['Cluster']==cluster, 0],
                X_pca[df['Cluster']==cluster, 1],
                label=f'Cluster {cluster}', s=50)

plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.title('Customer Segments (K-Means Clustering with PCA)')
plt.legend()
plt.show()
'''