# -*- coding: utf-8 -*-
"""Mall_customers(heirarchial)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ESkLVhlg1l40iIolCc1dR20RL1ZrRUb
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA

# Load dataset
df = pd.read_csv("Mall_Customers.csv")

# Select numeric features
X = df[['Age', 'Annual Income (k$)', 'S_score']]  # You can include Gender if desired

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Create AgglomerativeClustering object
agg_clust = AgglomerativeClustering(n_clusters=6,  # choose number of clusters
                                    linkage='ward')        # linkage method

# Fit and get cluster labels
labels = agg_clust.fit_predict(X_scaled)
df['Cluster'] = labels

# Reduce dimensions to 2D for plotting
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(8,6))
for cluster in sorted(df['Cluster'].unique()):
    plt.scatter(X_pca[df['Cluster']==cluster, 0],
                X_pca[df['Cluster']==cluster, 1],
                label=f'Cluster {cluster}', s=50)

plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.title('Hierarchical Clustering (Agglomerative)')
plt.legend()
plt.show()
'''
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load data
df = pd.read_csv("Mall_Customers.csv")
X = df[['Age', 'Annual Income (k$)', 'S_score']]

# Normalize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


# Fit Agglomerative Clustering
agg_clust = AgglomerativeClustering(n_clusters=6, linkage='ward')
labels = agg_clust.fit_predict(X_scaled)

# Compute silhouette score
score = silhouette_score(X_scaled, labels)
print(f"Silhouette Score: {score:.3f}")
'''