# -*- coding: utf-8 -*-
"""spam classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMO4daja9lb49uIT4wpdAbeH0VcdqHKx
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

# Load the dataset (skip any problematic lines while reading the CSV)
df = pd.read_csv('emails-2.csv', on_bad_lines='skip',engine='python')

# Identify any unwanted 'Unnamed:' columns created due to CSV formatting issues
unnamed_cols = [col for col in df.columns if 'Unnamed:' in col]

# Drop the unnecessary 'Unnamed:' columns
df = df.drop(columns=unnamed_cols)

# Remove rows that contain missing or null values
df.dropna(inplace=True)

# Define target (y) and features (X)
y=df['Spam']
X=df['Text']

# Split dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# Convert raw text into TF-IDF numerical vectors
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train)   # Learn vocab + transform training text
X_test = vectorizer.transform(X_test)         # Transform testing text

# Create and train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
confusionmatrix= confusion_matrix(y_test, y_pred)
classificationreport= classification_report(y_test, y_pred)

# Print results
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusionmatrix}")
print(f"Classification Report:\n{classificationreport}")


'''
msg = ['''You won a free laptop''']

msg_vec = vectorizer.transform(msg)
prediction = model.predict(msg_vec)

print("Spam" if prediction[0] == 1 else "Not Spam")
'''